# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cheneyee' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'YYKit'
  pod 'ReactiveObjC'
  pod 'IQKeyboardManager'
  pod 'MJRefresh'   
  pod 'AFNetworking'
  pod 'QMUIKit'
  # Pods for Cheneyee

end
